[tool.poetry]
name = "nemonet"
version = "0.5.21"
description = "Visual testing framework. Combining selenium and computer vision."
authors = ["Jan Rummens <jan.rummens@nemo.be>"]
license = "MIT License"


[tool.poetry.dependencies]
python = "^3.6"
atomicwrites = "^1.4.0"
attrs = "^20.2.0"
beautifulsoup4 = "^4.9.1"
certifi = "^2020.6.20"
colorama = "^0.4.3"
cycler = "^0.10.0"
decorator = "^4.4.2"
graphviz = "^0.14.1"
imageio = "^2.9.0"
importlib-metadata = "^1.7.0"
imutils = "^0.5.3"
iniconfig = "^1.0.1"
jira="^2.0.0"
kiwisolver = "^1.2.0"
lxml = "^4.5.2"
matplotlib = "^3.3.2"
more-itertools = "^8.5.0"
MouseInfo = "^0.1.3"
networkx = "^2.5"
numpy = "^1.19.2"
opencv-contrib-python = "^4.4.0.42"
packaging = "^20.4"
Pillow = "^7.2.0"
pluggy = "^0.13.1"
py = "^1.9.0"
PyAutoGUI = "^0.9.50"
PyGetWindow = "^0.0.8"
PyMsgBox = "^1.0.8"
pyparsing = "^2.4.7"
pyperclip = "^1.8.0"
PyRect = "^0.1.4"
PyScreeze = "^0.1.26"
pytest = "^6.0.2"
python-dateutil = "^2.8.1"
PyTweening = "^1.0.3"
PyWavelets = "^1.1.1"
scikit-image = "^0.17.2"
scipy = "^1.5.2"
selenium = "^3.141.0"
six = "^1.15.0"
soupsieve = "^2.0.1"
typer="^0.3.2"
tifffile = "^2020.9.3"
toml = "^0.10.1"
urllib3 = "^1.25.10"
zipp = "^3.1.0"
attrdict = "^2.0.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ['atomicwrites>=1.4.0','attrs>=20.2.0','beautifulsoup4>=4.9.1','certifi>=2020.6.20','colorama>=0.4.3','cycler>=0.10.0','decorator>=4.4.2','graphviz>=0.14.1','imageio>=2.9.0','importlib-metadata>=1.7.0','imutils>=0.5.3','iniconfig>=1.0.1','kiwisolver>=1.2.0','lxml>=4.5.2','matplotlib>=3.3.2','more-itertools>=8.5.0','MouseInfo>=0.1.3','networkx>=2.5','numpy>=1.19.2','opencv-contrib-python>=4.4.0.42','packaging>=20.4','Pillow>=7.2.0','pluggy>=0.13.1','py>=1.9.0','PyAutoGUI>=0.9.50','PyGetWindow>=0.0.8','PyMsgBox>=1.0.8','pyparsing>=2.4.7','pyperclip>=1.8.0','PyRect>=0.1.4','PyScreeze>=0.1.26','pytest>=6.0.2','python-dateutil>=2.8.1','PyTweening>=1.0.3','PyWavelets>=1.1.1','scikit-image>=0.17.2','scipy>=1.5.2','selenium>=3.141.0','six>=1.15.0','soupsieve>=2.0.1','tifffile>=2020.9.3','toml>=0.10.1','urllib3>=1.25.10','zipp>=3.1.0', 'attrdict>=2.0.1',]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
vision = "nemonet.main:app"