[tool.poetry]
name = "crazehub"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.3.0"
webbot = "^0.34"
phonenumbers = "^8.12.18"
scripts = "^2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
