[tool.poetry]
name = "sprint-datapusher"
version = "0.1.2"
description = "A tool to read csv files, transform to json and push to sprint_excel_webserver."
authors = ["Stig B. Dørmænen <stigbd@gmail.com>", "Heming Harnæs <heming.harnaes@gmail.com"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/heming-langrenn/sprint-excel/tree/main/datapusher"
repository = "https://github.com/heming-langrenn/sprint-excel"
classifiers=[
      "Programming Language :: Python :: 3",
      "License :: OSI Approved :: Apache Software License",
      "Operating System :: OS Independent",
      ]

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.3.1"
click = "^7.1.2"
jsonpickle = "^1.4.1"
watchdog = "^1.0.1"
pandas = "^1.1.5"
requests = "^2.25.1"
python-dotenv = "^0.15.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-black = "^0.2.1"
mypy = "^0.782"
pytype = {version = "^2020.2.20", python = "3.7"}
flake8-annotations = "^2.4.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
darglint = "^1.5.5"
flake8-assertive = "^1.2.1"
pytest-cov = "^2.10.1"
deepdiff = "^5.0.2"
pytest-mock = "^3.3.1"
pep8-naming = "^0.11.1"
safety = "^1.9.0"
codecov = "^2.1.10"

[tool.poetry.scripts]
sprint_datapusher = "sprint_datapusher.datapusher:cli"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = false
source = ["sprint_datapusher"]

[tool.coverage.report]
show_missing = true
fail_under = 50

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
